// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateEventMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventMessage) Reset()         { *m = CreateEventMessage{} }
func (m *CreateEventMessage) String() string { return proto.CompactTextString(m) }
func (*CreateEventMessage) ProtoMessage()    {}
func (*CreateEventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

func (m *CreateEventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventMessage.Unmarshal(m, b)
}
func (m *CreateEventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventMessage.Marshal(b, m, deterministic)
}
func (m *CreateEventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventMessage.Merge(m, src)
}
func (m *CreateEventMessage) XXX_Size() int {
	return xxx_messageInfo_CreateEventMessage.Size(m)
}
func (m *CreateEventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventMessage proto.InternalMessageInfo

func (m *CreateEventMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateEventMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateEventMessage)(nil), "proto.CreateEventMessage")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9) }

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2d, 0x4b, 0xcd,
	0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x4e, 0x5c, 0x42,
	0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0xae, 0x20, 0x49, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54,
	0x21, 0x31, 0x2e, 0xb6, 0xe2, 0x92, 0xc4, 0x92, 0xd2, 0x62, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x28, 0x4f, 0x48, 0x84, 0x8b, 0x35, 0xb5, 0xa8, 0x28, 0xbf, 0x48, 0x82, 0x09, 0x2c, 0x0c,
	0xe1, 0x18, 0xa5, 0xa0, 0x98, 0x11, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0xe4, 0xc7, 0x25,
	0x56, 0x9c, 0x9a, 0x97, 0x82, 0xc5, 0x74, 0x49, 0x88, 0x13, 0xf4, 0x30, 0xa5, 0xa4, 0x70, 0x4b,
	0x39, 0xb1, 0x47, 0x41, 0x9c, 0x9c, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd2, 0x6d, 0x1c, 0x7e, 0xd0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CreateEventServiceClient is the client API for CreateEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CreateEventServiceClient interface {
	SendCreateEventMessage(ctx context.Context, in *CreateEventMessage, opts ...grpc.CallOption) (*CreateEventMessage, error)
}

type createEventServiceClient struct {
	cc *grpc.ClientConn
}

func NewCreateEventServiceClient(cc *grpc.ClientConn) CreateEventServiceClient {
	return &createEventServiceClient{cc}
}

func (c *createEventServiceClient) SendCreateEventMessage(ctx context.Context, in *CreateEventMessage, opts ...grpc.CallOption) (*CreateEventMessage, error) {
	out := new(CreateEventMessage)
	err := c.cc.Invoke(ctx, "/proto.CreateEventService/sendCreateEventMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateEventServiceServer is the server API for CreateEventService service.
type CreateEventServiceServer interface {
	SendCreateEventMessage(context.Context, *CreateEventMessage) (*CreateEventMessage, error)
}

// UnimplementedCreateEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCreateEventServiceServer struct {
}

func (*UnimplementedCreateEventServiceServer) SendCreateEventMessage(ctx context.Context, req *CreateEventMessage) (*CreateEventMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCreateEventMessage not implemented")
}

func RegisterCreateEventServiceServer(s *grpc.Server, srv CreateEventServiceServer) {
	s.RegisterService(&_CreateEventService_serviceDesc, srv)
}

func _CreateEventService_SendCreateEventMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateEventServiceServer).SendCreateEventMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CreateEventService/SendCreateEventMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateEventServiceServer).SendCreateEventMessage(ctx, req.(*CreateEventMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _CreateEventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CreateEventService",
	HandlerType: (*CreateEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendCreateEventMessage",
			Handler:    _CreateEventService_SendCreateEventMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "events.proto",
}
