// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/events.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DateFk               uint32               `protobuf:"varint,2,opt,name=dateFk,proto3" json:"dateFk,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetDateFk() uint32 {
	if m != nil {
		return m.DateFk
	}
	return 0
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type Date struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Events               []*Event             `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{1}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Date) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Calendar struct {
	Dates                []*Date  `protobuf:"bytes,1,rep,name=dates,proto3" json:"dates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calendar) Reset()         { *m = Calendar{} }
func (m *Calendar) String() string { return proto.CompactTextString(m) }
func (*Calendar) ProtoMessage()    {}
func (*Calendar) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{2}
}

func (m *Calendar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calendar.Unmarshal(m, b)
}
func (m *Calendar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calendar.Marshal(b, m, deterministic)
}
func (m *Calendar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calendar.Merge(m, src)
}
func (m *Calendar) XXX_Size() int {
	return xxx_messageInfo_Calendar.Size(m)
}
func (m *Calendar) XXX_DiscardUnknown() {
	xxx_messageInfo_Calendar.DiscardUnknown(m)
}

var xxx_messageInfo_Calendar proto.InternalMessageInfo

func (m *Calendar) GetDates() []*Date {
	if m != nil {
		return m.Dates
	}
	return nil
}

type CreateEventResponseMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventResponseMessage) Reset()         { *m = CreateEventResponseMessage{} }
func (m *CreateEventResponseMessage) String() string { return proto.CompactTextString(m) }
func (*CreateEventResponseMessage) ProtoMessage()    {}
func (*CreateEventResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{3}
}

func (m *CreateEventResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventResponseMessage.Unmarshal(m, b)
}
func (m *CreateEventResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventResponseMessage.Marshal(b, m, deterministic)
}
func (m *CreateEventResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventResponseMessage.Merge(m, src)
}
func (m *CreateEventResponseMessage) XXX_Size() int {
	return xxx_messageInfo_CreateEventResponseMessage.Size(m)
}
func (m *CreateEventResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventResponseMessage proto.InternalMessageInfo

func (m *CreateEventResponseMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateEventResponseMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateEventResponseMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateEventRequestMessage struct {
	Title                string               `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,102,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateEventRequestMessage) Reset()         { *m = CreateEventRequestMessage{} }
func (m *CreateEventRequestMessage) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequestMessage) ProtoMessage()    {}
func (*CreateEventRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{4}
}

func (m *CreateEventRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequestMessage.Unmarshal(m, b)
}
func (m *CreateEventRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequestMessage.Marshal(b, m, deterministic)
}
func (m *CreateEventRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequestMessage.Merge(m, src)
}
func (m *CreateEventRequestMessage) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequestMessage.Size(m)
}
func (m *CreateEventRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequestMessage proto.InternalMessageInfo

func (m *CreateEventRequestMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateEventRequestMessage) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateEventRequestMessage) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type DeleteEventRequestMessage struct {
	EventId              uint64   `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventRequestMessage) Reset()         { *m = DeleteEventRequestMessage{} }
func (m *DeleteEventRequestMessage) String() string { return proto.CompactTextString(m) }
func (*DeleteEventRequestMessage) ProtoMessage()    {}
func (*DeleteEventRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{5}
}

func (m *DeleteEventRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventRequestMessage.Unmarshal(m, b)
}
func (m *DeleteEventRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventRequestMessage.Marshal(b, m, deterministic)
}
func (m *DeleteEventRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventRequestMessage.Merge(m, src)
}
func (m *DeleteEventRequestMessage) XXX_Size() int {
	return xxx_messageInfo_DeleteEventRequestMessage.Size(m)
}
func (m *DeleteEventRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventRequestMessage proto.InternalMessageInfo

func (m *DeleteEventRequestMessage) GetEventId() uint64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

type DeleteEventResponseMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventResponseMessage) Reset()         { *m = DeleteEventResponseMessage{} }
func (m *DeleteEventResponseMessage) String() string { return proto.CompactTextString(m) }
func (*DeleteEventResponseMessage) ProtoMessage()    {}
func (*DeleteEventResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{6}
}

func (m *DeleteEventResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventResponseMessage.Unmarshal(m, b)
}
func (m *DeleteEventResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventResponseMessage.Marshal(b, m, deterministic)
}
func (m *DeleteEventResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventResponseMessage.Merge(m, src)
}
func (m *DeleteEventResponseMessage) XXX_Size() int {
	return xxx_messageInfo_DeleteEventResponseMessage.Size(m)
}
func (m *DeleteEventResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventResponseMessage proto.InternalMessageInfo

func (m *DeleteEventResponseMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DeleteEventResponseMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type UpdateEventRequestMessage struct {
	EventId              uint64   `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEventRequestMessage) Reset()         { *m = UpdateEventRequestMessage{} }
func (m *UpdateEventRequestMessage) String() string { return proto.CompactTextString(m) }
func (*UpdateEventRequestMessage) ProtoMessage()    {}
func (*UpdateEventRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{7}
}

func (m *UpdateEventRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEventRequestMessage.Unmarshal(m, b)
}
func (m *UpdateEventRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEventRequestMessage.Marshal(b, m, deterministic)
}
func (m *UpdateEventRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEventRequestMessage.Merge(m, src)
}
func (m *UpdateEventRequestMessage) XXX_Size() int {
	return xxx_messageInfo_UpdateEventRequestMessage.Size(m)
}
func (m *UpdateEventRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEventRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEventRequestMessage proto.InternalMessageInfo

func (m *UpdateEventRequestMessage) GetEventId() uint64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *UpdateEventRequestMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateEventRequestMessage) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateEventResponseMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEventResponseMessage) Reset()         { *m = UpdateEventResponseMessage{} }
func (m *UpdateEventResponseMessage) String() string { return proto.CompactTextString(m) }
func (*UpdateEventResponseMessage) ProtoMessage()    {}
func (*UpdateEventResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{8}
}

func (m *UpdateEventResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEventResponseMessage.Unmarshal(m, b)
}
func (m *UpdateEventResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEventResponseMessage.Marshal(b, m, deterministic)
}
func (m *UpdateEventResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEventResponseMessage.Merge(m, src)
}
func (m *UpdateEventResponseMessage) XXX_Size() int {
	return xxx_messageInfo_UpdateEventResponseMessage.Size(m)
}
func (m *UpdateEventResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEventResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEventResponseMessage proto.InternalMessageInfo

func (m *UpdateEventResponseMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateEventResponseMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type GetEventsForDateRequestMessage struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsForDateRequestMessage) Reset()         { *m = GetEventsForDateRequestMessage{} }
func (m *GetEventsForDateRequestMessage) String() string { return proto.CompactTextString(m) }
func (*GetEventsForDateRequestMessage) ProtoMessage()    {}
func (*GetEventsForDateRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{9}
}

func (m *GetEventsForDateRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsForDateRequestMessage.Unmarshal(m, b)
}
func (m *GetEventsForDateRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsForDateRequestMessage.Marshal(b, m, deterministic)
}
func (m *GetEventsForDateRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsForDateRequestMessage.Merge(m, src)
}
func (m *GetEventsForDateRequestMessage) XXX_Size() int {
	return xxx_messageInfo_GetEventsForDateRequestMessage.Size(m)
}
func (m *GetEventsForDateRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsForDateRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsForDateRequestMessage proto.InternalMessageInfo

func (m *GetEventsForDateRequestMessage) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type GetEventsForDateResponseMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Events               []*Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsForDateResponseMessage) Reset()         { *m = GetEventsForDateResponseMessage{} }
func (m *GetEventsForDateResponseMessage) String() string { return proto.CompactTextString(m) }
func (*GetEventsForDateResponseMessage) ProtoMessage()    {}
func (*GetEventsForDateResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{10}
}

func (m *GetEventsForDateResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsForDateResponseMessage.Unmarshal(m, b)
}
func (m *GetEventsForDateResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsForDateResponseMessage.Marshal(b, m, deterministic)
}
func (m *GetEventsForDateResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsForDateResponseMessage.Merge(m, src)
}
func (m *GetEventsForDateResponseMessage) XXX_Size() int {
	return xxx_messageInfo_GetEventsForDateResponseMessage.Size(m)
}
func (m *GetEventsForDateResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsForDateResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsForDateResponseMessage proto.InternalMessageInfo

func (m *GetEventsForDateResponseMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetEventsForDateResponseMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *GetEventsForDateResponseMessage) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type GetEventsForMonthRequestMessage struct {
	Month                string   `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsForMonthRequestMessage) Reset()         { *m = GetEventsForMonthRequestMessage{} }
func (m *GetEventsForMonthRequestMessage) String() string { return proto.CompactTextString(m) }
func (*GetEventsForMonthRequestMessage) ProtoMessage()    {}
func (*GetEventsForMonthRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{11}
}

func (m *GetEventsForMonthRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsForMonthRequestMessage.Unmarshal(m, b)
}
func (m *GetEventsForMonthRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsForMonthRequestMessage.Marshal(b, m, deterministic)
}
func (m *GetEventsForMonthRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsForMonthRequestMessage.Merge(m, src)
}
func (m *GetEventsForMonthRequestMessage) XXX_Size() int {
	return xxx_messageInfo_GetEventsForMonthRequestMessage.Size(m)
}
func (m *GetEventsForMonthRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsForMonthRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsForMonthRequestMessage proto.InternalMessageInfo

func (m *GetEventsForMonthRequestMessage) GetMonth() string {
	if m != nil {
		return m.Month
	}
	return ""
}

type GetEventsForMonthResponseMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Events               []*Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsForMonthResponseMessage) Reset()         { *m = GetEventsForMonthResponseMessage{} }
func (m *GetEventsForMonthResponseMessage) String() string { return proto.CompactTextString(m) }
func (*GetEventsForMonthResponseMessage) ProtoMessage()    {}
func (*GetEventsForMonthResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{12}
}

func (m *GetEventsForMonthResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsForMonthResponseMessage.Unmarshal(m, b)
}
func (m *GetEventsForMonthResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsForMonthResponseMessage.Marshal(b, m, deterministic)
}
func (m *GetEventsForMonthResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsForMonthResponseMessage.Merge(m, src)
}
func (m *GetEventsForMonthResponseMessage) XXX_Size() int {
	return xxx_messageInfo_GetEventsForMonthResponseMessage.Size(m)
}
func (m *GetEventsForMonthResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsForMonthResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsForMonthResponseMessage proto.InternalMessageInfo

func (m *GetEventsForMonthResponseMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetEventsForMonthResponseMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *GetEventsForMonthResponseMessage) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type GetEventsForIntervalRequestMessage struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Till                 string   `protobuf:"bytes,2,opt,name=till,proto3" json:"till,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsForIntervalRequestMessage) Reset()         { *m = GetEventsForIntervalRequestMessage{} }
func (m *GetEventsForIntervalRequestMessage) String() string { return proto.CompactTextString(m) }
func (*GetEventsForIntervalRequestMessage) ProtoMessage()    {}
func (*GetEventsForIntervalRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{13}
}

func (m *GetEventsForIntervalRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsForIntervalRequestMessage.Unmarshal(m, b)
}
func (m *GetEventsForIntervalRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsForIntervalRequestMessage.Marshal(b, m, deterministic)
}
func (m *GetEventsForIntervalRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsForIntervalRequestMessage.Merge(m, src)
}
func (m *GetEventsForIntervalRequestMessage) XXX_Size() int {
	return xxx_messageInfo_GetEventsForIntervalRequestMessage.Size(m)
}
func (m *GetEventsForIntervalRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsForIntervalRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsForIntervalRequestMessage proto.InternalMessageInfo

func (m *GetEventsForIntervalRequestMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetEventsForIntervalRequestMessage) GetTill() string {
	if m != nil {
		return m.Till
	}
	return ""
}

type GetEventsForIntervalResponseMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Events               []*Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsForIntervalResponseMessage) Reset()         { *m = GetEventsForIntervalResponseMessage{} }
func (m *GetEventsForIntervalResponseMessage) String() string { return proto.CompactTextString(m) }
func (*GetEventsForIntervalResponseMessage) ProtoMessage()    {}
func (*GetEventsForIntervalResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{14}
}

func (m *GetEventsForIntervalResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsForIntervalResponseMessage.Unmarshal(m, b)
}
func (m *GetEventsForIntervalResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsForIntervalResponseMessage.Marshal(b, m, deterministic)
}
func (m *GetEventsForIntervalResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsForIntervalResponseMessage.Merge(m, src)
}
func (m *GetEventsForIntervalResponseMessage) XXX_Size() int {
	return xxx_messageInfo_GetEventsForIntervalResponseMessage.Size(m)
}
func (m *GetEventsForIntervalResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsForIntervalResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsForIntervalResponseMessage proto.InternalMessageInfo

func (m *GetEventsForIntervalResponseMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetEventsForIntervalResponseMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *GetEventsForIntervalResponseMessage) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type GetEventByIdResponseMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Event                *Event   `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventByIdResponseMessage) Reset()         { *m = GetEventByIdResponseMessage{} }
func (m *GetEventByIdResponseMessage) String() string { return proto.CompactTextString(m) }
func (*GetEventByIdResponseMessage) ProtoMessage()    {}
func (*GetEventByIdResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{15}
}

func (m *GetEventByIdResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventByIdResponseMessage.Unmarshal(m, b)
}
func (m *GetEventByIdResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventByIdResponseMessage.Marshal(b, m, deterministic)
}
func (m *GetEventByIdResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventByIdResponseMessage.Merge(m, src)
}
func (m *GetEventByIdResponseMessage) XXX_Size() int {
	return xxx_messageInfo_GetEventByIdResponseMessage.Size(m)
}
func (m *GetEventByIdResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventByIdResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventByIdResponseMessage proto.InternalMessageInfo

func (m *GetEventByIdResponseMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetEventByIdResponseMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetEventByIdResponseMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetEventByIdResponseMessage) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type GetEventByIdRequestMessage struct {
	EventId              uint64   `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventByIdRequestMessage) Reset()         { *m = GetEventByIdRequestMessage{} }
func (m *GetEventByIdRequestMessage) String() string { return proto.CompactTextString(m) }
func (*GetEventByIdRequestMessage) ProtoMessage()    {}
func (*GetEventByIdRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{16}
}

func (m *GetEventByIdRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventByIdRequestMessage.Unmarshal(m, b)
}
func (m *GetEventByIdRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventByIdRequestMessage.Marshal(b, m, deterministic)
}
func (m *GetEventByIdRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventByIdRequestMessage.Merge(m, src)
}
func (m *GetEventByIdRequestMessage) XXX_Size() int {
	return xxx_messageInfo_GetEventByIdRequestMessage.Size(m)
}
func (m *GetEventByIdRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventByIdRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventByIdRequestMessage proto.InternalMessageInfo

func (m *GetEventByIdRequestMessage) GetEventId() uint64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

type GetEventsForTimeIntervalRequestMessage struct {
	From                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Till                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=till,proto3" json:"till,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetEventsForTimeIntervalRequestMessage) Reset() {
	*m = GetEventsForTimeIntervalRequestMessage{}
}
func (m *GetEventsForTimeIntervalRequestMessage) String() string { return proto.CompactTextString(m) }
func (*GetEventsForTimeIntervalRequestMessage) ProtoMessage()    {}
func (*GetEventsForTimeIntervalRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{17}
}

func (m *GetEventsForTimeIntervalRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsForTimeIntervalRequestMessage.Unmarshal(m, b)
}
func (m *GetEventsForTimeIntervalRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsForTimeIntervalRequestMessage.Marshal(b, m, deterministic)
}
func (m *GetEventsForTimeIntervalRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsForTimeIntervalRequestMessage.Merge(m, src)
}
func (m *GetEventsForTimeIntervalRequestMessage) XXX_Size() int {
	return xxx_messageInfo_GetEventsForTimeIntervalRequestMessage.Size(m)
}
func (m *GetEventsForTimeIntervalRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsForTimeIntervalRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsForTimeIntervalRequestMessage proto.InternalMessageInfo

func (m *GetEventsForTimeIntervalRequestMessage) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GetEventsForTimeIntervalRequestMessage) GetTill() *timestamp.Timestamp {
	if m != nil {
		return m.Till
	}
	return nil
}

type GetEventsForTimeIntervalResponseMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Events               []*Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsForTimeIntervalResponseMessage) Reset() {
	*m = GetEventsForTimeIntervalResponseMessage{}
}
func (m *GetEventsForTimeIntervalResponseMessage) String() string { return proto.CompactTextString(m) }
func (*GetEventsForTimeIntervalResponseMessage) ProtoMessage()    {}
func (*GetEventsForTimeIntervalResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_499cf8c2dd86f7dd, []int{18}
}

func (m *GetEventsForTimeIntervalResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsForTimeIntervalResponseMessage.Unmarshal(m, b)
}
func (m *GetEventsForTimeIntervalResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsForTimeIntervalResponseMessage.Marshal(b, m, deterministic)
}
func (m *GetEventsForTimeIntervalResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsForTimeIntervalResponseMessage.Merge(m, src)
}
func (m *GetEventsForTimeIntervalResponseMessage) XXX_Size() int {
	return xxx_messageInfo_GetEventsForTimeIntervalResponseMessage.Size(m)
}
func (m *GetEventsForTimeIntervalResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsForTimeIntervalResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsForTimeIntervalResponseMessage proto.InternalMessageInfo

func (m *GetEventsForTimeIntervalResponseMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetEventsForTimeIntervalResponseMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *GetEventsForTimeIntervalResponseMessage) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*Date)(nil), "proto.Date")
	proto.RegisterType((*Calendar)(nil), "proto.Calendar")
	proto.RegisterType((*CreateEventResponseMessage)(nil), "proto.CreateEventResponseMessage")
	proto.RegisterType((*CreateEventRequestMessage)(nil), "proto.CreateEventRequestMessage")
	proto.RegisterType((*DeleteEventRequestMessage)(nil), "proto.DeleteEventRequestMessage")
	proto.RegisterType((*DeleteEventResponseMessage)(nil), "proto.DeleteEventResponseMessage")
	proto.RegisterType((*UpdateEventRequestMessage)(nil), "proto.UpdateEventRequestMessage")
	proto.RegisterType((*UpdateEventResponseMessage)(nil), "proto.UpdateEventResponseMessage")
	proto.RegisterType((*GetEventsForDateRequestMessage)(nil), "proto.GetEventsForDateRequestMessage")
	proto.RegisterType((*GetEventsForDateResponseMessage)(nil), "proto.GetEventsForDateResponseMessage")
	proto.RegisterType((*GetEventsForMonthRequestMessage)(nil), "proto.GetEventsForMonthRequestMessage")
	proto.RegisterType((*GetEventsForMonthResponseMessage)(nil), "proto.GetEventsForMonthResponseMessage")
	proto.RegisterType((*GetEventsForIntervalRequestMessage)(nil), "proto.GetEventsForIntervalRequestMessage")
	proto.RegisterType((*GetEventsForIntervalResponseMessage)(nil), "proto.GetEventsForIntervalResponseMessage")
	proto.RegisterType((*GetEventByIdResponseMessage)(nil), "proto.GetEventByIdResponseMessage")
	proto.RegisterType((*GetEventByIdRequestMessage)(nil), "proto.GetEventByIdRequestMessage")
	proto.RegisterType((*GetEventsForTimeIntervalRequestMessage)(nil), "proto.GetEventsForTimeIntervalRequestMessage")
	proto.RegisterType((*GetEventsForTimeIntervalResponseMessage)(nil), "proto.GetEventsForTimeIntervalResponseMessage")
}

func init() { proto.RegisterFile("proto/events.proto", fileDescriptor_499cf8c2dd86f7dd) }

var fileDescriptor_499cf8c2dd86f7dd = []byte{
	// 727 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5d, 0x4f, 0xd4, 0x40,
	0x14, 0x4d, 0x77, 0xb7, 0x0b, 0x7b, 0x17, 0x8d, 0x99, 0x18, 0x52, 0xaa, 0x91, 0x32, 0x28, 0xac,
	0x26, 0x94, 0x04, 0xbf, 0xde, 0x01, 0x51, 0x8c, 0xbc, 0x54, 0x7d, 0x21, 0xfa, 0x50, 0xe8, 0x05,
	0x1b, 0xba, 0xed, 0xda, 0x19, 0x10, 0xe2, 0x83, 0x2f, 0x3e, 0xe8, 0x2f, 0xf0, 0x57, 0xfa, 0x1f,
	0xcc, 0x4c, 0x3b, 0x6b, 0xa7, 0xdb, 0x76, 0x91, 0xc8, 0xd3, 0x76, 0x3a, 0xf7, 0x9e, 0x73, 0x7a,
	0xe6, 0xce, 0xc9, 0x02, 0x19, 0xa5, 0x09, 0x4f, 0xd6, 0xf1, 0x0c, 0x63, 0xce, 0x5c, 0xb9, 0x20,
	0xa6, 0xfc, 0xb1, 0x17, 0x8f, 0x93, 0xe4, 0x38, 0xc2, 0x75, 0xb9, 0x3a, 0x38, 0x3d, 0x5a, 0xe7,
	0xe1, 0x10, 0x19, 0xf7, 0x87, 0xa3, 0xac, 0x8e, 0xfe, 0x32, 0xc0, 0x7c, 0x21, 0x1a, 0xc9, 0x4d,
	0x68, 0x85, 0x81, 0x65, 0x38, 0xc6, 0xa0, 0xe3, 0xb5, 0xc2, 0x80, 0xcc, 0x43, 0x37, 0xf0, 0x39,
	0xee, 0x9c, 0x58, 0x2d, 0xc7, 0x18, 0xdc, 0xf0, 0xf2, 0x15, 0xb9, 0x0d, 0x26, 0x0f, 0x79, 0x84,
	0x56, 0xdb, 0x31, 0x06, 0x3d, 0x2f, 0x5b, 0x10, 0x07, 0xfa, 0x01, 0xb2, 0xc3, 0x34, 0x1c, 0xf1,
	0x30, 0x89, 0xad, 0x8e, 0xdc, 0x2b, 0xbe, 0x22, 0x2e, 0x74, 0x04, 0xb9, 0x65, 0x3a, 0xc6, 0xa0,
	0xbf, 0x61, 0xbb, 0x99, 0x32, 0x57, 0x29, 0x73, 0xdf, 0x29, 0x65, 0x9e, 0xac, 0xa3, 0x1f, 0xa0,
	0xb3, 0xed, 0x73, 0x14, 0x7d, 0x82, 0x59, 0x2a, 0x9b, 0xd2, 0x27, 0xea, 0xc8, 0x7d, 0xe8, 0x66,
	0x4e, 0x58, 0x2d, 0xa7, 0x3d, 0xe8, 0x6f, 0xcc, 0x65, 0xa5, 0xae, 0xfc, 0x4a, 0x2f, 0xdf, 0xa3,
	0x6b, 0x30, 0xbb, 0xe5, 0x47, 0x18, 0x07, 0x7e, 0x4a, 0x96, 0xc0, 0x14, 0x9d, 0xcc, 0x32, 0x64,
	0x43, 0x3f, 0x6f, 0x10, 0xec, 0x5e, 0xb6, 0x43, 0xf7, 0xc1, 0xde, 0x4a, 0xd1, 0xe7, 0x98, 0xa1,
	0x20, 0x1b, 0x25, 0x31, 0xc3, 0x3d, 0x64, 0xcc, 0x3f, 0x46, 0x61, 0x15, 0xe3, 0x3e, 0x3f, 0x65,
	0x52, 0x64, 0xcf, 0xcb, 0x57, 0xc2, 0x2a, 0x4c, 0xd3, 0x24, 0x95, 0x0e, 0xf6, 0xbc, 0x6c, 0x91,
	0x1b, 0xdd, 0x56, 0x46, 0xd3, 0x9f, 0x06, 0x2c, 0x68, 0xe0, 0x9f, 0x4f, 0x91, 0x71, 0x85, 0x3d,
	0xb6, 0xdb, 0x68, 0xb0, 0xbb, 0x55, 0x6f, 0xf7, 0xd1, 0xe5, 0xec, 0x7e, 0xdd, 0x99, 0x6d, 0xdf,
	0x42, 0xfa, 0x14, 0x16, 0xb6, 0x31, 0xc2, 0x6a, 0x29, 0x16, 0xcc, 0x48, 0xf7, 0x76, 0xd5, 0x98,
	0xa8, 0x25, 0x7d, 0x05, 0xb6, 0xd6, 0x76, 0x39, 0x7b, 0x08, 0x74, 0x38, 0x9e, 0xf3, 0x5c, 0xbd,
	0x7c, 0xa6, 0x43, 0x58, 0x78, 0x3f, 0x0a, 0xfc, 0x7f, 0x14, 0xf0, 0xd7, 0xa5, 0x56, 0x83, 0x4b,
	0xed, 0x09, 0x97, 0x84, 0x70, 0x8d, 0xee, 0xea, 0xc2, 0x9f, 0xc0, 0xbd, 0x97, 0xc8, 0x25, 0x0c,
	0xdb, 0x49, 0x52, 0x39, 0x3c, 0xba, 0x7a, 0x52, 0x18, 0xe4, 0x5e, 0x36, 0xac, 0x94, 0xc1, 0xe2,
	0x64, 0xd7, 0x95, 0x45, 0x14, 0x66, 0xbf, 0xdd, 0x30, 0xfb, 0xcf, 0x75, 0xd2, 0xbd, 0x24, 0xe6,
	0x9f, 0x26, 0xa7, 0x6e, 0x28, 0x5e, 0xab, 0xa9, 0x93, 0x0b, 0xca, 0xc1, 0xa9, 0x68, 0xbc, 0x6e,
	0xb9, 0x6f, 0x80, 0x16, 0x59, 0x77, 0x63, 0x8e, 0xe9, 0x99, 0x1f, 0x4d, 0xba, 0x7b, 0x94, 0x26,
	0x43, 0xe5, 0xae, 0x78, 0x96, 0x9c, 0x61, 0x14, 0x8d, 0x39, 0xc3, 0x28, 0xa2, 0x5f, 0x60, 0xb9,
	0x1a, 0xed, 0xba, 0x3f, 0xe3, 0x1b, 0xdc, 0x51, 0xc4, 0x9b, 0x17, 0xbb, 0xc1, 0x7f, 0xcd, 0x10,
	0x42, 0xc1, 0x94, 0x34, 0x32, 0x78, 0xcb, 0x0a, 0xb2, 0x2d, 0xfa, 0x0c, 0x6c, 0x5d, 0xc0, 0x25,
	0x2f, 0xf7, 0x0f, 0x03, 0x56, 0x8a, 0x96, 0x89, 0xe4, 0xa8, 0x39, 0x04, 0xb7, 0x70, 0x08, 0x53,
	0x42, 0x47, 0x1e, 0x90, 0x5b, 0x38, 0xa0, 0xa9, 0x21, 0x15, 0x45, 0xf4, 0x2b, 0xac, 0xd6, 0x2b,
	0xb9, 0xe6, 0x03, 0xdc, 0xf8, 0xdd, 0x85, 0x39, 0xf9, 0xe6, 0x2d, 0xa6, 0x67, 0xe1, 0x21, 0x92,
	0x8f, 0x30, 0xcf, 0x30, 0x0e, 0x0a, 0xd9, 0xad, 0xc8, 0x9d, 0x1c, 0xa0, 0x36, 0xd6, 0xed, 0xa5,
	0xaa, 0x0a, 0xfd, 0x0b, 0x72, 0xf8, 0x42, 0xb0, 0x96, 0xe1, 0x6b, 0xa3, 0x7a, 0x0c, 0xdf, 0x90,
	0xca, 0x39, 0x7c, 0x21, 0xfe, 0xca, 0xf0, 0xb5, 0x41, 0x3c, 0x86, 0x6f, 0xc8, 0xce, 0x13, 0xb0,
	0x05, 0xbc, 0x9e, 0x6e, 0x17, 0x6a, 0xf7, 0x41, 0x0e, 0xd0, 0x1c, 0x99, 0xf6, 0x4a, 0x6d, 0x99,
	0x4e, 0x96, 0xc0, 0xdd, 0x32, 0x99, 0x0c, 0x27, 0xb5, 0x5f, 0x85, 0x53, 0x11, 0x7b, 0xf6, 0x6a,
	0x7d, 0x9d, 0x4e, 0x78, 0x0e, 0x8b, 0x65, 0x42, 0x35, 0x88, 0xaa, 0xe4, 0x61, 0x05, 0x56, 0xf5,
	0xb5, 0xb1, 0x1f, 0x35, 0x96, 0xea, 0xcc, 0x3e, 0x58, 0x1a, 0xb3, 0xb8, 0xca, 0x6a, 0x6f, 0xa9,
	0x84, 0x33, 0x79, 0xcd, 0x6d, 0x5a, 0x59, 0xa2, 0x53, 0x7c, 0x37, 0x60, 0xb9, 0xfc, 0x75, 0xc5,
	0xab, 0xa6, 0xea, 0xd6, 0x2a, 0x64, 0xd7, 0x87, 0x83, 0xed, 0x4e, 0x2d, 0xd7, 0x64, 0x6c, 0xce,
	0xec, 0x67, 0x7f, 0x62, 0x0f, 0xba, 0xf2, 0xe7, 0xf1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c,
	0xb6, 0x67, 0x54, 0xe8, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	SendCreateEventMessage(ctx context.Context, in *CreateEventRequestMessage, opts ...grpc.CallOption) (*CreateEventResponseMessage, error)
	SendDeleteEventMessage(ctx context.Context, in *DeleteEventRequestMessage, opts ...grpc.CallOption) (*DeleteEventResponseMessage, error)
	SendUpdateEventMessage(ctx context.Context, in *UpdateEventRequestMessage, opts ...grpc.CallOption) (*UpdateEventResponseMessage, error)
	SendGetEventsForDayMessage(ctx context.Context, in *GetEventsForDateRequestMessage, opts ...grpc.CallOption) (*GetEventsForDateResponseMessage, error)
	SendGetEventsForMonthMessage(ctx context.Context, in *GetEventsForMonthRequestMessage, opts ...grpc.CallOption) (*GetEventsForMonthResponseMessage, error)
	SendGetEventsForIntervalMessage(ctx context.Context, in *GetEventsForIntervalRequestMessage, opts ...grpc.CallOption) (*GetEventsForIntervalResponseMessage, error)
	SendGetEventsByIdMessage(ctx context.Context, in *GetEventByIdRequestMessage, opts ...grpc.CallOption) (*GetEventByIdResponseMessage, error)
	SendGetEventsForTimeIntervalMessage(ctx context.Context, in *GetEventsForTimeIntervalRequestMessage, opts ...grpc.CallOption) (*GetEventsForTimeIntervalResponseMessage, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) SendCreateEventMessage(ctx context.Context, in *CreateEventRequestMessage, opts ...grpc.CallOption) (*CreateEventResponseMessage, error) {
	out := new(CreateEventResponseMessage)
	err := c.cc.Invoke(ctx, "/proto.EventService/sendCreateEventMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SendDeleteEventMessage(ctx context.Context, in *DeleteEventRequestMessage, opts ...grpc.CallOption) (*DeleteEventResponseMessage, error) {
	out := new(DeleteEventResponseMessage)
	err := c.cc.Invoke(ctx, "/proto.EventService/sendDeleteEventMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SendUpdateEventMessage(ctx context.Context, in *UpdateEventRequestMessage, opts ...grpc.CallOption) (*UpdateEventResponseMessage, error) {
	out := new(UpdateEventResponseMessage)
	err := c.cc.Invoke(ctx, "/proto.EventService/sendUpdateEventMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SendGetEventsForDayMessage(ctx context.Context, in *GetEventsForDateRequestMessage, opts ...grpc.CallOption) (*GetEventsForDateResponseMessage, error) {
	out := new(GetEventsForDateResponseMessage)
	err := c.cc.Invoke(ctx, "/proto.EventService/sendGetEventsForDayMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SendGetEventsForMonthMessage(ctx context.Context, in *GetEventsForMonthRequestMessage, opts ...grpc.CallOption) (*GetEventsForMonthResponseMessage, error) {
	out := new(GetEventsForMonthResponseMessage)
	err := c.cc.Invoke(ctx, "/proto.EventService/sendGetEventsForMonthMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SendGetEventsForIntervalMessage(ctx context.Context, in *GetEventsForIntervalRequestMessage, opts ...grpc.CallOption) (*GetEventsForIntervalResponseMessage, error) {
	out := new(GetEventsForIntervalResponseMessage)
	err := c.cc.Invoke(ctx, "/proto.EventService/sendGetEventsForIntervalMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SendGetEventsByIdMessage(ctx context.Context, in *GetEventByIdRequestMessage, opts ...grpc.CallOption) (*GetEventByIdResponseMessage, error) {
	out := new(GetEventByIdResponseMessage)
	err := c.cc.Invoke(ctx, "/proto.EventService/sendGetEventsByIdMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SendGetEventsForTimeIntervalMessage(ctx context.Context, in *GetEventsForTimeIntervalRequestMessage, opts ...grpc.CallOption) (*GetEventsForTimeIntervalResponseMessage, error) {
	out := new(GetEventsForTimeIntervalResponseMessage)
	err := c.cc.Invoke(ctx, "/proto.EventService/sendGetEventsForTimeIntervalMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	SendCreateEventMessage(context.Context, *CreateEventRequestMessage) (*CreateEventResponseMessage, error)
	SendDeleteEventMessage(context.Context, *DeleteEventRequestMessage) (*DeleteEventResponseMessage, error)
	SendUpdateEventMessage(context.Context, *UpdateEventRequestMessage) (*UpdateEventResponseMessage, error)
	SendGetEventsForDayMessage(context.Context, *GetEventsForDateRequestMessage) (*GetEventsForDateResponseMessage, error)
	SendGetEventsForMonthMessage(context.Context, *GetEventsForMonthRequestMessage) (*GetEventsForMonthResponseMessage, error)
	SendGetEventsForIntervalMessage(context.Context, *GetEventsForIntervalRequestMessage) (*GetEventsForIntervalResponseMessage, error)
	SendGetEventsByIdMessage(context.Context, *GetEventByIdRequestMessage) (*GetEventByIdResponseMessage, error)
	SendGetEventsForTimeIntervalMessage(context.Context, *GetEventsForTimeIntervalRequestMessage) (*GetEventsForTimeIntervalResponseMessage, error)
}

// UnimplementedEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (*UnimplementedEventServiceServer) SendCreateEventMessage(ctx context.Context, req *CreateEventRequestMessage) (*CreateEventResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCreateEventMessage not implemented")
}
func (*UnimplementedEventServiceServer) SendDeleteEventMessage(ctx context.Context, req *DeleteEventRequestMessage) (*DeleteEventResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDeleteEventMessage not implemented")
}
func (*UnimplementedEventServiceServer) SendUpdateEventMessage(ctx context.Context, req *UpdateEventRequestMessage) (*UpdateEventResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendUpdateEventMessage not implemented")
}
func (*UnimplementedEventServiceServer) SendGetEventsForDayMessage(ctx context.Context, req *GetEventsForDateRequestMessage) (*GetEventsForDateResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGetEventsForDayMessage not implemented")
}
func (*UnimplementedEventServiceServer) SendGetEventsForMonthMessage(ctx context.Context, req *GetEventsForMonthRequestMessage) (*GetEventsForMonthResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGetEventsForMonthMessage not implemented")
}
func (*UnimplementedEventServiceServer) SendGetEventsForIntervalMessage(ctx context.Context, req *GetEventsForIntervalRequestMessage) (*GetEventsForIntervalResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGetEventsForIntervalMessage not implemented")
}
func (*UnimplementedEventServiceServer) SendGetEventsByIdMessage(ctx context.Context, req *GetEventByIdRequestMessage) (*GetEventByIdResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGetEventsByIdMessage not implemented")
}
func (*UnimplementedEventServiceServer) SendGetEventsForTimeIntervalMessage(ctx context.Context, req *GetEventsForTimeIntervalRequestMessage) (*GetEventsForTimeIntervalResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGetEventsForTimeIntervalMessage not implemented")
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_SendCreateEventMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SendCreateEventMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/SendCreateEventMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SendCreateEventMessage(ctx, req.(*CreateEventRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SendDeleteEventMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SendDeleteEventMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/SendDeleteEventMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SendDeleteEventMessage(ctx, req.(*DeleteEventRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SendUpdateEventMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SendUpdateEventMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/SendUpdateEventMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SendUpdateEventMessage(ctx, req.(*UpdateEventRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SendGetEventsForDayMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsForDateRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SendGetEventsForDayMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/SendGetEventsForDayMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SendGetEventsForDayMessage(ctx, req.(*GetEventsForDateRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SendGetEventsForMonthMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsForMonthRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SendGetEventsForMonthMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/SendGetEventsForMonthMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SendGetEventsForMonthMessage(ctx, req.(*GetEventsForMonthRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SendGetEventsForIntervalMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsForIntervalRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SendGetEventsForIntervalMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/SendGetEventsForIntervalMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SendGetEventsForIntervalMessage(ctx, req.(*GetEventsForIntervalRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SendGetEventsByIdMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventByIdRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SendGetEventsByIdMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/SendGetEventsByIdMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SendGetEventsByIdMessage(ctx, req.(*GetEventByIdRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SendGetEventsForTimeIntervalMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsForTimeIntervalRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SendGetEventsForTimeIntervalMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/SendGetEventsForTimeIntervalMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SendGetEventsForTimeIntervalMessage(ctx, req.(*GetEventsForTimeIntervalRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendCreateEventMessage",
			Handler:    _EventService_SendCreateEventMessage_Handler,
		},
		{
			MethodName: "sendDeleteEventMessage",
			Handler:    _EventService_SendDeleteEventMessage_Handler,
		},
		{
			MethodName: "sendUpdateEventMessage",
			Handler:    _EventService_SendUpdateEventMessage_Handler,
		},
		{
			MethodName: "sendGetEventsForDayMessage",
			Handler:    _EventService_SendGetEventsForDayMessage_Handler,
		},
		{
			MethodName: "sendGetEventsForMonthMessage",
			Handler:    _EventService_SendGetEventsForMonthMessage_Handler,
		},
		{
			MethodName: "sendGetEventsForIntervalMessage",
			Handler:    _EventService_SendGetEventsForIntervalMessage_Handler,
		},
		{
			MethodName: "sendGetEventsByIdMessage",
			Handler:    _EventService_SendGetEventsByIdMessage_Handler,
		},
		{
			MethodName: "sendGetEventsForTimeIntervalMessage",
			Handler:    _EventService_SendGetEventsForTimeIntervalMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/events.proto",
}
