version: '3.7'

#networks:
#  db:
#    driver: bridge
#  grpc_server:
#    driver: bridge
#  rabbit:
#    driver: bridge

networks:
  apinet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.99.0/24

services:
  manager-postgres:
    image: postgres:11.3-alpine
    container_name: dbpg
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    #      - ./storage/docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: md
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: md_calendar
    ports:
      - "54321:5432"
    networks:
      apinet:
        ipv4_address: 172.30.99.51

  rabbit:
    image: "rabbitmq:3-management"
    container_name: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      apinet:
        ipv4_address: 172.30.99.53

  grpc_server:
    build: ./server
    container_name: grpc
    restart: on-failure
    depends_on:
      - manager-postgres
    environment:
      REG_SERVICE_DB_USER: md
      REG_SERVICE_DB_PASSWORD: secret
      REG_SERVICE_DB_NAME: md_calendar
      REG_SERVICE_DB_HOST: dbpg
      REG_SERVICE_DB_PORT: 5432
      REG_SERVICE_LOG_LEVEL: info
      REG_SERVICE_WEB_PORT: 8888
      REG_SERVICE_GRPC_PORT: 50054
      REG_SERVICE_LISTEN_IP: 0.0.0.0
    ports:
      - "8888:8888"
    networks:
      apinet:
        ipv4_address: 172.30.99.50

  scheduler:
    build: ./scheduler
    restart: on-failure
    depends_on:
      - manager-postgres
      - rabbit
      - grpc_server
    environment:
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      LOG_LEVEL: info
      GRPC_PORT: 50054
      GRPC_HOST: grpc
      LISTEN_IP: 0.0.0.0
    networks:
      apinet:
        ipv4_address: 172.30.99.55

  message_server:
    build: ./message_office
    depends_on:
      - scheduler
      - rabbit
    restart: on-failure
    environment:
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      LOG_LEVEL: info
    networks:
      apinet:
        ipv4_address: 172.30.99.60
