version: '3'

networks:
  db:
    driver: bridge
#  grpc_server:
#    driver: bridge

services:
  manager-postgres:
    image: postgres:11.3-alpine
    container_name: dbpg
    volumes:
      - ./storage/docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: md
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: md_calendar
    ports:
      - "54321:5432"
    networks:
      - db

#  grpc_server:
#    build: ./server
#    container_name: grpc
#    depends_on:
#      - manager-postgres
#    ports:
#      - "8888:8888"
#    networks:
#      - grpc_server
#      - db